### ISSUE TITLE
Cannot scan subsequent VuMarks for JSON data

### ISSUE THREAD

**Issue by andreamtang** [ubcemergingmedialab/ARDesign#19]
Cannot make new JSON requests on VuMarks after successfully retrieving information from one VuMark:

```
Coroutine couldn't be started because the the game object 'VuMark' is inactive!
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Origin:Init(String) (at Assets/Scripts/Origin.cs:32)
VuMarkHandler:OnVuMarkDetected(VuMarkTarget) (at Assets/Scripts/VuMarkHandler.cs:66)
```

**Comment by unoctium1** [comment]
I think this isn't an issue. If a VuMark contains scene info for one room, I think it makes sense that we should only be handling one vumark at a time. 

This is probably an issue with how the hololens and vuforia deal with extended tracking though, I believe once Vuforia detects a target, if its configured for the hololens, it basically turns itself off and passes control to the hololen's spatial coordinate system
